---->How many patients are there in each gender?
SELECT gender,
       COUNT(*) AS total_patients
FROM patients
GROUP BY gender;
---->How many doctors work in each specialization?
SELECT specialization,
       COUNT(*) AS total_doctors
FROM doctors
GROUP BY specialization;
---->Total revenue generated by each payment method.
SELECT payment_method,
       SUM(amount) AS total_revenue
FROM billing
GROUP BY payment_method;
---->How many appointments are there for each appointment status?
SELECT status,
       COUNT(*) AS total_appointments
FROM appointments
GROUP BY status;
---->Average treatment cost for each treatment type.
SELECT treatment_type,
       AVG(cost) AS average_cost
FROM treatments
GROUP BY treatment_type;
---->How many patients belong to each insurance provider?
SELECT insurance_provider,
       COUNT(*) AS total_patients
FROM patients
GROUP BY insurance_provider
ORDER BY total_patients DESC;
---->Highest bill amount for each payment method.
SELECT payment_method,
       MAX(amount) AS highest_bill
FROM billing
GROUP BY payment_method;
---->Average experience for each specialization.
SELECT specialization,
       AVG(years_experience) AS average_experience
FROM doctors
GROUP BY specialization
ORDER BY average_experience DESC;
---->How many completed appointments has each doctor handled?
SELECT doctor_id,
       COUNT(*) AS completed_appointments
FROM appointments
WHERE status = 'Completed'
GROUP BY doctor_id;
---->Total bill amount for each patient?
SELECT patient_id,
       SUM(amount) AS total_bill_amount
FROM billing
GROUP BY patient_id
ORDER BY total_bill_amount DESC;
---->Highest treatment cost for each treatment type?
SELECT treatment_type,
       MAX(cost) AS highest_cost
FROM treatments
GROUP BY treatment_type;
---->Appointments on each appointment date?
SELECT appointment_date,
       COUNT(*) AS total_appointments
FROM appointments
GROUP BY appointment_date
ORDER BY appointment_date;
---->Average bill amount for each payment status?
SELECT payment_status,
       AVG(amount) AS average_bill
FROM billing
GROUP BY payment_status;
---->Minimum experience in each specialization?
SELECT specialization,
       MIN(years_experience) AS minimum_experience
FROM doctors
GROUP BY specialization;
---->Number of patients under each insurance provider?
SELECT insurance_provider,
       COUNT(*) AS total_patients
FROM patients
GROUP BY insurance_provider;
---->Finance Dashboard.For each payment method show:Total Bills,Total Revenue,Average Bill,Highest Bill,Lowest Bill
SELECT payment_method,
       COUNT(*) AS total_bills,
       SUM(amount) AS total_revenue,
       AVG(amount) AS average_bill,
       MAX(amount) AS highest_bill,
       MIN(amount) AS lowest_bill
FROM billing
GROUP BY payment_method
ORDER BY total_revenue DESC;
---->CEO Dashboard.For each specialization show:Total Doctors,Average Experience,Highest Experience,Lowest Experience
SELECT specialization,
       COUNT(*) AS total_doctors,
       AVG(years_experience) AS average_experience,
       MAX(years_experience) AS highest_experience,
       MIN(years_experience) AS lowest_experience
FROM doctors
GROUP BY specialization
ORDER BY average_experience DESC;
---->For each appointment status show:Total Appointments,Earliest Appointment,Latest Appointment
SELECT status,
       COUNT(*) AS total_appointments,
       MIN(appointment_date) AS earliest_appointment,
       MAX(appointment_date) AS latest_appointment
FROM appointments
GROUP BY status;
---->For each treatment type show:Total Treatments,Average Cost,Highest Cost,Lowest Cost
SELECT treatment_type,
       COUNT(*) AS total_treatments,
       AVG(cost) AS average_cost,
       MAX(cost) AS highest_cost,
       MIN(cost) AS lowest_cost
FROM treatments
GROUP BY treatment_type
ORDER BY average_cost DESC;
---->For each insurance provider show:Total Patients,Oldest Patient DOB,Youngest Patient DOB
SELECT insurance_provider,
       COUNT(*) AS total_patients,
       MIN(date_of_birth) AS oldest_patient_dob,
       MAX(date_of_birth) AS youngest_patient_dob
FROM patients
GROUP BY insurance_provider
ORDER BY total_patients DESC;
